[
    { activities_type_id: 1, description: "Time off and leave", has_number: 0, has_item: 0, has_description: 1, has_estimated_time: 0 },
    { activities_type_id: 2, description: "Company processes", has_number: 0, has_item: 0, has_description: 1, has_estimated_time: 0 },
    { activities_type_id: 3, description: "Coding and development", has_number: 2, has_item: 2, has_description: 1, has_estimated_time: 1 },
    { activities_type_id: 4, description: "Miscellaneous", has_number: 0, has_item: 0, has_description: 1, has_estimated_time: 0 },
    { activities_type_id: 5, description: "Health and wellness", has_number: 0, has_item: 0, has_description: 1, has_estimated_time: 0 },
    { activities_type_id: 6, description: "Analysis", has_number: 2, has_item: 0, has_description: 1, has_estimated_time: 0 },
]

[
    { description: 'DB2', activies_type_id: 4, active: 0 },
    { description: 'Iniciando e Configurando Ferramentas de Trabalho', activies_type_id: 4, active: 1 },
    { description: 'Phase 2 - Requirements and Planning', activies_type_id: 0, active: 0 },
    { description: 'Phase 3 - Design', activies_type_id: 0, active: 0 },
    { description: 'Phase 4 - Development', activies_type_id: 0, active: 0 },
    { description: 'Phase 5 - Systems Testing', activies_type_id: 0, active: 0 },
    { description: 'Projetos', activies_type_id: 4, active: 0 },
    { description: 'RA', activies_type_id: 4, active: 0 },
    { description: 'RDM', activies_type_id: 4, active: 0 },
    { description: 'Registrando Atividades no Registro de Atividades', activies_type_id: 4, active: 1 },
    { description: 'Respondendo Dúvida da Equipe', activies_type_id: 4, active: 0 },
    { description: 'Reunião', activies_type_id: 4, active: 1 },
    { description: 'Reunião Daily/Weekly', activies_type_id: 4, active: 1 },
    { description: 'Reuniões de Versão (EBS)', activies_type_id: 4, active: 0 },
    { description: 'SAI - Análise - Reunião de diversas SAIs', activies_type_id: 4, active: 0 },
    { description: 'SAI - Análise - Reunião de SAI especifica', activies_type_id: 4, active: 0 },
    { description: 'SAI - CodeReview', activies_type_id: 0, active: 0 },
    { description: 'SAIL-Analisando SAIL', activies_type_id: 6, active: 1 },
    { description: 'SAI - Merge', activies_type_id: 0, active: 0 },
    { description: 'SAI - Programação', activies_type_id: 3, active: 1 },
    { description: 'SAI - Respondendo duvidas a gerencia de produtos', activies_type_id: 0, active: 0 },
    { description: 'SAI - Respondendo duvidas ao Teste', activies_type_id: 0, active: 0 },
    { description: 'SAI - Retornos', activies_type_id: 0, active: 0 },
    { description: 'SAL-Analisando SAL', activies_type_id: 6, active: 1 },
    { description: 'SAM-Analisando SAM', activies_type_id: 6, active: 1 },
    { description: 'SCSQL', activies_type_id: 6, active: 1 },
    { description: 'SQL (Auxílio)', activies_type_id: 6, active: 1 },
    { description: 'SS', activies_type_id: 6, active: 1 },
    { description: 'SS (Auxílio)', activies_type_id: 6, active: 1 },
    { description: 'SSI', activies_type_id: 0, active: 0 },
    { description: 'SSI (Auxílios)', activies_type_id: 0, active: 0 },
    { description: 'Suporte', activies_type_id: 0, active: 0 },
    { description: 'Tarefas do SGD', activies_type_id: 0, active: 0 },
    { description: 'Treinamento (fornecendo)', activies_type_id: 4, active: 1 },
    { description: 'Treinamento (recebendo)', activies_type_id: 4, active: 1 },
    { description: 'Utilitários', activies_type_id: 4, active: 1 },
    { description: 'Validando roteiros de desenvolvimento', activies_type_id: 0, active: 0 },
    { description: 'Versão', activies_type_id: 4, active: 1 },
    { description: 'Versão - Auxiliando Destraves', activies_type_id: 4, active: 1 },
    { description: 'Afastamento Doença', activies_type_id: 1, active: 1 },
    { description: 'Area Folha - Aperfeiçoamento', activies_type_id: 2, active: 0 },
    { description: 'Atualizando/Reiniciando Aplicações em PROD', activies_type_id: 2, active: 1 },
    { description: 'Atualizando Ambiente de Testes', activies_type_id: 2, active: 1 },
    { description: 'Auxílio Maternidade', activies_type_id: 1, active: 1 },
    { description: 'Classificando retorno de teste', activies_type_id: 2, active: 1 },
    { description: 'Conferindo/Assinando Relatório Ponto', activies_type_id: 2, active: 1 },
    { description: 'Consulta Médica', activies_type_id: 5, active: 1 },
    { description: 'Contabil - Gerenciamento', activies_type_id: 2, active: 1 },
    { description: 'Diretrizes - Outros', activies_type_id: 2, active: 1 },
    { description: 'Diretrizes - PDCA', activies_type_id: 2, active: 1 },
    { description: 'Estudo para versões futuras', activies_type_id: 2, active: 1 },
    { description: 'Feedback funcionários', activies_type_id: 2, active: 1 },
    { description: 'Feriado', activies_type_id: 1, active: 1 },
    { description: 'Férias', activies_type_id: 1, active: 1 },
    { description: 'Folga Aniversário', activies_type_id: 1, active: 1 },
    { description: 'Folga banco de horas', activies_type_id: 1, active: 1 },
    { description: 'Folga concedida pela Empresa', activies_type_id: 1, active: 1 },
    { description: 'Folga Funeral', activies_type_id: 1, active: 1 },
    { description: 'Folga Matrimônio', activies_type_id: 1, active: 1 },
    { description: 'Folga Paternidade', activies_type_id: 1, active: 1 },
    { description: 'Lanche', activies_type_id: 4, active: 1 },
    { description: 'Merge e Deploy Liberação Versão/Arquivo', activies_type_id: 4, active: 1 },
    { description: 'MyExpenses', activies_type_id: 4, active: 1 },
    { description: 'my_time - Lançar tempos', activies_type_id: 4, active: 1 },
    { description: 'NE/SA', activies_type_id: 6, active: 1 },
    { description: 'NE-Analisando NE', activies_type_id: 6, active: 1 },
    { description: 'OnBalance OOB', activies_type_id: 4, active: 1 },
    { description: 'ONVIO', activies_type_id: 4, active: 1 },
    { description: 'ONVIO/ONBALANCE - Anomalias', activies_type_id: 4, active: 1 },
    { description: 'Outros: Emails', activies_type_id: 4, active: 1 },
    { description: 'Outros ** Evite Usar', activies_type_id: 4, active: 1 },
    { description: 'Participando de TOWN HALL', activies_type_id: 2, active: 1 },
    { description: 'Pesquisa', activies_type_id: 4, active: 1 },
    { description: 'Pessoal', activies_type_id: 4, active: 1 },
    { description: 'PSAI - Análise', activies_type_id: 3, active: 1 },
    { description: 'SAI - Auxílio', activies_type_id: 3, active: 1 },
    { description: 'Saída Particular', activies_type_id: 1, active: 1 },
]